version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore Furesoft.Signals/Furesoft.Signals.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish Furesoft.Signals/Furesoft.Signals.csproj --output %appveyor_build_folder%\dist

build:
  verbosity: minimal
after_build:
- cmd: dotnet publish Furesoft.Signals --output %appveyor_build_folder%\dist

clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off