version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore Furesoft.Signals/Furesoft.Signals.csproj --verbosity m
  
build:
  verbosity: minimal
  
after_build:
- cmd: dotnet publish Furesoft.Signals --output %appveyor_build_folder%

clone_depth: 1

deploy:
  provider: NuGet
  api_key:
    secure: Qi2ST6B2VSqjhKVXiZa1ncyvRvTZ1J3b6v5GFsYOdc734Tzbg5Wexogz2ZC59C2g
  skip_symbols: false