version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

build:
  verbosity: minimal
after_build:
- cmd: dotnet publish Furesoft.Signals --output %appveyor_build_folder%\dist

clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off